### ISSUE TITLE
Config generation

### ISSUE THREAD

**Issue by 0x111** [sn-edit/vscode#13]
The config generation should be done in multiple steps.

- [ ] Someone runs command, generate config
- [ ] The extension downloads the sample yaml file from here: https://github.com/sn-edit/sn-edit/blob/master/_config/sn-edit.sample.yaml
- [ ] After download, we parse the yaml into some kind of object and display choices based on the yaml file
- [ ] Everything under the core key is mandatory, so users have to fill out through the UI the following details
```yaml
  core:
    log_level: info
    rate_limit: 2
    db:
      path: /path/to/db/file
      initialised: false
    rest:
      masked: false
      password: password
      url: https://dev111.service-now.com
      user: admin
      xor_key: randomxorkey
    root_directory: /path/to/scripts/folder/tmp
```
- [ ] Ask the user for each input separately, so first he would set the log level. That can be one of these:
https://github.com/sn-edit/sn-edit/blob/f0a64fd5ced9f2c9850527f66e0ffcff3032e149/conf/conf.go#L31-L47
See the strings there. (debug, info etc.)
The user should pick one in Vscode and this would be written to that value
- [ ] Rate limit is a historical option, leave it at 2, optinally it will disappear
- [ ] Db path is a path to the database file locally, it should be a valid path.
If you can pick files in vscode, then we should use that, if not, default of this option is the current workspace path. 
Let the user write the whole path. Only a full path is allowed here.
- [ ] After submission, validate if the db path is valid. The folder described should exist, but the file will be automatically created by sn-edit if nonexistent.
- [ ] Another bigger topic here are the rest credentials. The user provides a username and password for these so please request that from them through the UI.
  - [ ] Show input for username and password
  - [ ] Ask for the xor_key, this is used for masking the password so we do not store plaintext values
- [ ] The root_directory is also mandatory, ask for it and after submission validate if the directory exists.
